import { useEffect, useState, createContext, useContext } from "react";
import { BrowserRouter, Routes, Route, Link, NavLink, useNavigate, useLocation, Navigate } from "react-router-dom";
import axios from "axios";
import { ArrowRight, CalendarDays, CheckCircle2, ChevronDown, Home, Leaf, LogOut, MapPin, Menu, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const api = axios.create({ baseURL: API, withCredentials: true });
const AuthContext = createContext(null);
const useAuth = () => useContext(AuthContext);
const LOGO_URL = "https://customer-assets-lqy194kg.emergentagent.net/job_codelytics-1/artifacts/n4s35m8f_Nirnay%20Group.webp";
function Brand({ light = false }) { return <span className={`nirnay-brand ${light ? "nirnay-brand-light" : ""}`}><img src={LOGO_URL} alt="Nirnay Group logo"/><span>Nirnay<span className="brand-light"> Group</span></span></span>; }

function AuthProvider({ children }) {
  const [user, setUser] = useState(null); const [checking, setChecking] = useState(true);
  useEffect(() => { api.get("/auth/me").then(r => setUser(r.data)).catch(() => {}).finally(() => setChecking(false)); }, []);
  const logout = async () => { await api.post("/auth/logout"); setUser(null); };
  return <AuthContext.Provider value={{ user, setUser, logout, checking }}>{children}</AuthContext.Provider>;
}

function PublicHeader() { const [open, setOpen] = useState(false); return <header className="site-header"><Link to="/" className="brand" data-testid="brand-home"><Brand light/></Link><nav className={open ? "public-nav open" : "public-nav"}><NavLink to="/projects" data-testid="nav-projects">Projects</NavLink><NavLink to="/properties" data-testid="nav-properties">Properties</NavLink><NavLink to="/gallery" data-testid="nav-gallery">Gallery</NavLink><NavLink to="/about" data-testid="nav-about">Our story</NavLink><NavLink to="/contact" data-testid="nav-contact">Contact</NavLink><Link to="/book-site-visit" className="nav-cta" data-testid="nav-site-visit">Book a visit <ArrowRight size={15}/></Link></nav><button className="icon-button mobile-menu" onClick={() => setOpen(!open)} data-testid="mobile-menu-button">{open ? <X/> : <Menu/>}</button></header> }

function PublicLayout({ children }) { return <><PublicHeader/>{children}<footer className="site-footer"><div><Link to="/" className="brand"><Brand/></Link><p>Places with room to become your own.</p></div><div className="footer-links"><Link to="/projects">Projects</Link><Link to="/contact">Contact</Link><Link to="/associate/login">Associate login</Link><Link to="/admin/login">Admin login</Link></div><div className="footer-copy">© 2026 Nirnay Group</div></footer></> }

function Button({ children, to, onClick, secondary=false, type="button", testid }) { const className = secondary ? "button button-secondary" : "button"; return to ? <Link className={className} to={to} data-testid={testid}>{children}<ArrowRight size={16}/></Link> : <button className={className} onClick={onClick} type={type} data-testid={testid}>{children}{!secondary && <ArrowRight size={16}/>}</button> }

function HomePage() { return <PublicLayout><main><section className="hero"><div className="hero-image"></div><div className="hero-overlay"></div><div className="hero-content"><div className="eyebrow light"><Sparkles size={14}/> Places that feel like yours</div><h1>Make room for<br/><em>what matters.</em></h1><p>Thoughtfully planned homes and plots for people who want a little more life around them.</p><div className="hero-actions"><Button to="/projects" testid="hero-explore-projects">Explore projects</Button><Link to="/book-site-visit" className="text-link light-link" data-testid="hero-book-visit">Book a private visit <ArrowRight size={17}/></Link></div></div><div className="hero-note"><span>01</span><span>Homes & land, considered differently</span></div></section><section className="section intro-section"><div className="section-kicker">A better starting point</div><div className="intro-grid"><h2>Not just a plot.<br/><em>A place to belong.</em></h2><div><p className="large-copy">We create considered spaces that give you more than an address — a setting for your next chapter, with nature, community and everyday ease built in.</p><Link to="/about" className="text-link" data-testid="home-story-link">Discover our approach <ArrowRight size={17}/></Link></div></div></section><FeaturedProjects/><section className="quote-band"><div className="quote-mark">“</div><blockquote>There is a quiet confidence in a place designed to last.</blockquote><p>— The Verdant principle</p></section><section className="section visit-banner"><div><div className="section-kicker">Come see for yourself</div><h2>Your next<br/><em>view starts here.</em></h2></div><Button to="/book-site-visit" testid="home-visit-cta">Book a private visit</Button></section></main></PublicLayout> }

function FeaturedProjects() { const [projects, setProjects] = useState([]); useEffect(() => { api.get("/public/projects").then(r => setProjects(r.data)); }, []); return <section className="section projects-section"><div className="section-heading"><div><div className="section-kicker">Our places</div><h2>Made for <em>living well.</em></h2></div><Link to="/projects" className="text-link" data-testid="view-all-projects">View all projects <ArrowRight size={17}/></Link></div><div className="project-grid">{projects.map((p, i) => <Link to={`/projects/${p.slug}`} className={`project-card ${i === 0 ? "featured" : ""}`} key={p.id} data-testid={`project-card-${p.slug}`}><img src={p.image} alt={p.name}/><div className="project-card-content"><span>{p.location}</span><h3>{p.name}</h3><p>{p.tagline}</p><ArrowRight className="card-arrow" size={20}/></div></Link>)}</div></section> }

function ProjectsPage() { const [projects, setProjects] = useState([]); useEffect(() => { api.get("/public/projects").then(r => setProjects(r.data)); }, []); return <PublicLayout><PageIntro eyebrow="Our places" title={<>Projects with <em>perspective.</em></>} copy="From green neighbourhoods to considered plots, explore places made for the way life actually unfolds."/><section className="section"><div className="project-grid">{projects.map(p => <Link to={`/projects/${p.slug}`} className="project-card featured" key={p.id} data-testid={`projects-card-${p.slug}`}><img src={p.image} alt={p.name}/><div className="project-card-content"><span>{p.location} · {p.area}</span><h3>{p.name}</h3><p>{p.description}</p><ArrowRight className="card-arrow" size={20}/></div></Link>)}</div></section></PublicLayout> }

function ProjectDetail({ slug }) { const [project, setProject] = useState(null); useEffect(() => { api.get(`/public/projects/${slug}`).then(r => setProject(r.data)); }, [slug]); if (!project) return <PublicLayout><div className="loading">Loading project…</div></PublicLayout>; return <PublicLayout><section className="detail-hero"><img src={project.image} alt={project.name}/><div className="detail-hero-copy"><div className="eyebrow light">{project.location}</div><h1>{project.name}</h1><p>{project.tagline}</p></div></section><section className="section detail-grid"><div><div className="section-kicker">The feeling</div><h2>Space to grow<br/><em>into your life.</em></h2></div><div><p className="large-copy">{project.description}</p><div className="detail-stats"><div><strong>{project.area}</strong><span>of considered land</span></div><div><strong>From ₹{(project.price_from/100000).toFixed(1)}L</strong><span>starting investment</span></div></div></div></section><section className="section properties-section"><div className="section-heading"><div><div className="section-kicker">Availability</div><h2>Find your <em>place.</em></h2></div><Button to="/book-site-visit" testid="detail-book-visit">Book a visit</Button></div><div className="property-table">{project.properties.map(p => <div className="property-row" key={p.id} data-testid={`property-row-${p.number}`}><div><strong>{p.number}</strong><span>{p.size} · {p.facing} facing</span></div><strong>₹{(p.price/100000).toFixed(1)}L</strong><span className={`status status-${p.status}`}>{p.status}</span><Link to="/contact" className="row-link">Enquire <ArrowRight size={15}/></Link></div>)}</div></section></PublicLayout> }

function PropertiesPage() { const [properties, setProperties] = useState([]); useEffect(() => { api.get("/public/properties").then(r => setProperties(r.data)); }, []); return <PublicLayout><PageIntro eyebrow="Available now" title={<>A place for every <em>possibility.</em></>} copy="Browse current availability and find a plot that feels right for your plans."/><section className="section"><div className="property-table">{properties.map(p => <div className="property-row" key={p.id} data-testid={`public-property-${p.number}`}><div><strong>{p.number}</strong><span>{p.size} · {p.facing} facing</span></div><strong>₹{(p.price/100000).toFixed(1)}L</strong><span className={`status status-${p.status}`}>{p.status}</span><Link to="/contact" className="row-link">Enquire <ArrowRight size={15}/></Link></div>)}</div></section></PublicLayout> }

function PageIntro({ eyebrow, title, copy }) { return <section className="page-intro"><div className="section-kicker">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></section> }

function FormPage({ visit=false }) { const [form, setForm] = useState({}); const [done, setDone] = useState(false); const [error, setError] = useState(""); const submit = async e => { e.preventDefault(); setError(""); try { await api.post(visit ? "/public/site-visits" : "/public/inquiries", form); setDone(true); } catch (err) { setError(err.response?.data?.detail || "Please check your details and try again."); } }; if (done) return <PublicLayout><div className="success-state"><CheckCircle2 size={48}/><div className="section-kicker">Thank you</div><h1>{visit ? "Your visit is on its way." : "We'll be in touch."}</h1><p>Our team will contact you shortly with the next steps.</p><Button to="/" testid="form-success-home">Back to home</Button></div></PublicLayout>; return <PublicLayout><section className="form-page"><div className="form-copy"><div className="section-kicker">{visit ? "A little closer" : "Start a conversation"}</div><h1>{visit ? <>See it<br/><em>in person.</em></> : <>Let's find<br/><em>your place.</em></>}</h1><p>{visit ? "Tell us when you would like to visit. We'll make the experience personal, relaxed and entirely yours." : "Share a few details and our team will help you find the right project or property."}</p></div><form className="lead-form" onSubmit={submit}><label>Your name<input required data-testid="inquiry-name-input" onChange={e => setForm({...form, name:e.target.value})}/></label><label>Phone number<input required data-testid="inquiry-phone-input" onChange={e => setForm({...form, phone:e.target.value})}/></label><label>Email address<input type="email" data-testid="inquiry-email-input" onChange={e => setForm({...form, email:e.target.value})}/></label>{visit && <><label>Preferred date<input required type="date" data-testid="visit-date-input" onChange={e => setForm({...form, preferred_date:e.target.value})}/></label><label>Preferred time<select data-testid="visit-time-select" onChange={e => setForm({...form, preferred_time:e.target.value})}><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label></>}<label>How can we help?<textarea data-testid="inquiry-message-input" rows="4" onChange={e => setForm({...form, message:e.target.value})}/></label>{error && <div className="form-error" data-testid="form-error">{error}</div>}<Button type="submit" testid="inquiry-submit-button">{visit ? "Request my visit" : "Send enquiry"}</Button></form></section></PublicLayout> }

function GalleryPage() { return <PublicLayout><PageIntro eyebrow="A sense of place" title={<>Life, <em>beautifully framed.</em></>} copy="A glimpse into the details, textures and open skies that shape a Verdant place."/><section className="section gallery-grid"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85" alt="Warm modern living room"/><img src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=85" alt="Open plan interior"/><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=85" alt="Natural light interior"/><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85" alt="Elegant home detail"/></section></PublicLayout> }

function AboutPage() { return <PublicLayout><PageIntro eyebrow="Our story" title={<>Built around<br/><em>the good life.</em></>} copy="Verdant Estates began with a simple belief: the places we build should leave people feeling more grounded, more connected and more at home."/><section className="section about-band"><div className="about-image"></div><div><div className="section-kicker">The Verdant difference</div><h2>Thoughtful by<br/><em>nature.</em></h2><p className="large-copy">We look closely at how people live, then build with patience — choosing better materials, protecting open space and making every detail feel considered.</p></div></section></PublicLayout> }

function LoginPage({ role }) { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const { user, setUser } = useAuth(); const navigate = useNavigate(); if (user) return <Navigate to={user.role === "super_admin" ? "/admin/dashboard" : "/associate/dashboard"}/>; const submit = async e => { e.preventDefault(); try { const r = await api.post("/auth/login", {email,password}); if ((role === "admin" && r.data.role !== "super_admin") || (role === "associate" && r.data.role !== "associate")) throw new Error("This login is not available for this portal."); setUser(r.data); navigate(role === "admin" ? "/admin/dashboard" : "/associate/dashboard"); } catch (err) { setError(err.response?.data?.detail || err.message); } }; return <div className="portal-login"><div className="login-visual"><Link to="/" className="brand light-brand"><Brand light/></Link><div><div className="eyebrow light"><ShieldCheck size={14}/> {role === "admin" ? "Admin workspace" : "Associate workspace"}</div><h1>Good work<br/><em>starts here.</em></h1></div></div><form className="login-form" onSubmit={submit}><div className="section-kicker">{role === "admin" ? "Team access" : "Partner access"}</div><h2>Sign in to your workspace</h2><p>Use the credentials provided by your administrator.</p><label>Email address<input required type="email" data-testid="login-email-input" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" data-testid="login-password-input" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error && <div className="form-error" data-testid="login-error">{error}</div>}<Button type="submit" testid="login-submit-button">Sign in</Button><Link to="/" className="text-link back-link">Return to website</Link></form></div> }

function PortalLayout({ children, title }) { const { user, logout } = useAuth(); const navigate = useNavigate(); const admin = title === "Admin"; if (!user) return <Navigate to={admin ? "/admin/login" : "/associate/login"}/>; if ((admin && user.role !== "super_admin") || (!admin && user.role !== "associate")) return <Navigate to={admin ? "/associate/dashboard" : "/admin/dashboard"} replace/>; const links = admin ? [["Dashboard","/admin/dashboard",Home],["Leads","/admin/leads",Users],["Reservations","/admin/reservations",CalendarDays]] : [["Dashboard","/associate/dashboard",Home],["My leads","/associate/leads",Users],["Site visits","/associate/site-visits",CalendarDays],["Properties","/associate/properties",MapPin]]; return <div className="portal-shell"><aside className="portal-sidebar"><Link to="/" className="brand"><Brand/></Link><div className="portal-role">{admin ? "ADMIN CONSOLE" : "ASSOCIATE PORTAL"}</div><nav className="portal-nav">{links.map(([label,to,Icon])=><NavLink key={to} to={to} data-testid={`portal-nav-${label.toLowerCase().replaceAll(" ","-")}`}><Icon size={17}/>{label}</NavLink>)}</nav><div className="sidebar-user"><div className="avatar">{user.name?.charAt(0)}</div><div><strong>{user.name}</strong><span>{admin ? "Super admin" : "Associate"}</span></div><button className="icon-button" onClick={async()=>{await logout();navigate("/")}} data-testid="logout-button"><LogOut size={16}/></button></div></aside><main className="portal-main"><div className="portal-top"><div><span className="muted-label">{admin ? "Admin workspace" : "Your workspace"}</span><h1>{children}</h1></div><div className="portal-date">{new Date().toLocaleDateString("en-IN", {weekday:"long", day:"numeric", month:"long"})}</div></div></main></div> }

function Dashboard({ admin=false }) { const { user } = useAuth(); const [data,setData] = useState({}); useEffect(()=>{if (!user || (admin ? user.role !== "super_admin" : user.role !== "associate")) return; api.get(admin?"/admin/dashboard":"/associate/dashboard").then(r=>setData(r.data)).catch(()=>{});},[admin,user]); const cards=admin ? [["projects","Projects"],["properties","Properties"],["available","Available properties"],["leads","All leads"],["associates","Associates"],["pending_leads","Unassigned leads"]] : [["leads","My leads"],["follow_ups","Pending follow-ups"],["visits","Site visits"],["reservations","Reservations"],["bookings","Bookings"]]; return <PortalLayout title={admin ? "Admin" : "Associate"}><>{admin ? "Good morning" : `Welcome, ${user?.name?.split(" ")[0]}`}<div className="dashboard-content"><div className="metric-grid">{cards.map(([key,label])=><div className="metric-card" key={key} data-testid={`metric-${key}`}><span>{label}</span><strong>{data[key] ?? "—"}</strong><div className="metric-line"></div></div>)}</div><div className="portal-callout"><div><div className="section-kicker">{admin ? "Keep things moving" : "Your next best action"}</div><h2>{admin ? "A clear view of every opportunity." : "Every conversation can become a place."}</h2><p>{admin ? "Assign new enquiries quickly and keep your sales team focused on the people who need them most." : "Stay close to your leads, follow up thoughtfully and make every visit count."}</p></div><Sparkles size={48}/></div></div></></PortalLayout> }

function LeadsPage({ admin=false }) { const [leads,setLeads]=useState([]); const [associates,setAssociates]=useState([]); const load=()=>api.get(admin?"/admin/leads":"/associate/leads").then(r=>setLeads(r.data)); useEffect(()=>{load(); if(admin) api.get("/admin/associates").then(r=>setAssociates(r.data));},[]); const update=async(id,status)=>{await api.patch(`/associate/leads/${id}/status`,{status});load()}; const assign=async(e,id)=>{await api.patch(`/admin/leads/${id}/assign`,{associate_id:e.target.value});load()}; return <PortalLayout title={admin?"Admin":"Associate"}><>{admin?"Lead pipeline":"My leads"}<div className="dashboard-content"><div className="page-toolbar"><div><div className="section-kicker">{leads.length} active records</div><h2>{admin ? "All enquiries" : "People to follow up"}</h2></div></div><div className="lead-list">{leads.map(l=><div className="lead-row" key={l.id} data-testid={`lead-row-${l.id}`}><div className="lead-avatar">{l.name?.charAt(0)}</div><div className="lead-main"><strong>{l.name}</strong><span>{l.phone} {l.email && `· ${l.email}`}</span><small>{l.message || "No note added yet"}</small></div><span className={`status status-${l.status}`}>{l.status}</span>{admin ? <select value={l.assigned_associate_id || ""} onChange={e=>assign(e,l.id)} data-testid={`assign-lead-${l.id}`}><option value="">Assign associate</option>{associates.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select> : <select value={l.status} onChange={e=>update(l.id,e.target.value)} data-testid={`lead-status-${l.id}`}><option value="new">New</option><option value="contacted">Contacted</option><option value="interested">Interested</option><option value="visit_scheduled">Visit scheduled</option><option value="visited">Visited</option><option value="negotiation">Negotiation</option><option value="reserved">Reserved</option><option value="booked">Booked</option><option value="sold">Sold</option></select>}</div>)}</div>{!leads.length && <div className="empty-state">No leads yet — new website enquiries will appear here.</div>}</div></></PortalLayout> }

function SimplePortalPage({ type }) { const [items,setItems]=useState([]); const {user}=useAuth(); useEffect(()=>{const path=type==="properties"?"/associate/properties":"/associate/site-visits";api.get(path).then(r=>setItems(r.data));},[]); return <PortalLayout title="Associate">{type === "properties" ? "Property availability" : "My site visits"}<div className="dashboard-content"><div className="section-kicker">{items.length} records</div><h2>{type === "properties" ? "Find the right fit" : "Upcoming conversations"}</h2><div className="property-table portal-table">{items.map(x=><div className="property-row" key={x.id} data-testid={`${type}-row-${x.id}`}><div><strong>{x.number || x.visit_date}</strong><span>{x.size || x.preferred_time || "Scheduled"}</span></div><span className={`status status-${x.status}`}>{x.status}</span><span>{x.facing || x.notes || "—"}</span>{type === "properties" && x.status === "available" && <Button secondary to="/contact" testid={`property-enquire-${x.id}`}>Reserve through a lead</Button>}</div>)}</div></div></PortalLayout> }

function App() { return <AuthProvider><BrowserRouter><Routes><Route path="/" element={<HomePage/>}/><Route path="/projects" element={<ProjectsPage/>}/><Route path="/projects/:slug" element={<ProjectRoute/>}/><Route path="/properties" element={<PropertiesPage/>}/><Route path="/gallery" element={<GalleryPage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="/contact" element={<FormPage/>}/><Route path="/book-site-visit" element={<FormPage visit/>}/><Route path="/associate/login" element={<LoginPage role="associate"/>}/><Route path="/admin/login" element={<LoginPage role="admin"/>}/><Route path="/associate/dashboard" element={<Dashboard/>}/><Route path="/associate/leads" element={<LeadsPage/>}/><Route path="/associate/site-visits" element={<SimplePortalPage type="visits"/>}/><Route path="/associate/properties" element={<SimplePortalPage type="properties"/>}/><Route path="/admin/dashboard" element={<Dashboard admin/>}/><Route path="/admin/leads" element={<LeadsPage admin/>}/><Route path="/admin/reservations" element={<SimplePortalPage type="reservations"/>}/></Routes></BrowserRouter></AuthProvider> }
function ProjectRoute(){const {slug}=require("react-router-dom").useParams(); return <ProjectDetail slug={slug}/>}
export default App;